package net.digitalingot.feather;

import com.google.common.collect.ImmutableMap;
import com.google.common.collect.Maps;
import java.util.Map;

public class ik {
   public static final Map<Integer, String> a = ImmutableMap.builder()
      .put(Maps.immutableEntry(0, "P"))
      .put(Maps.immutableEntry(1, "FP"))
      .put(Maps.immutableEntry(2, "FF"))
      .put(Maps.immutableEntry(3, "BP"))
      .put(Maps.immutableEntry(4, "PP"))
      .put(Maps.immutableEntry(5, "R"))
      .put(Maps.immutableEntry(6, "AA"))
      .put(Maps.immutableEntry(7, "T"))
      .put(Maps.immutableEntry(8, "DS"))
      .put(Maps.immutableEntry(9, "FW"))
      .put(Maps.immutableEntry(16, "SH"))
      .put(Maps.immutableEntry(17, "SM"))
      .put(Maps.immutableEntry(18, "BoA"))
      .put(Maps.immutableEntry(19, "KB"))
      .put(Maps.immutableEntry(20, "FA"))
      .put(Maps.immutableEntry(21, "L"))
      .put(Maps.immutableEntry(32, "EFF"))
      .put(Maps.immutableEntry(33, "ST"))
      .put(Maps.immutableEntry(34, "UNB"))
      .put(Maps.immutableEntry(35, "F"))
      .put(Maps.immutableEntry(48, "POW"))
      .put(Maps.immutableEntry(49, "PUN"))
      .put(Maps.immutableEntry(50, "FLA"))
      .put(Maps.immutableEntry(51, "INF"))
      .put(Maps.immutableEntry(61, "LoS"))
      .put(Maps.immutableEntry(62, "LU"))
      .put(Maps.immutableEntry(70, "MEN"))
      .build();
   public static final Map<Integer, String> b = ImmutableMap.builder()
      .put(Maps.immutableEntry(1, "Spe"))
      .put(Maps.immutableEntry(2, "Slo"))
      .put(Maps.immutableEntry(3, "Has"))
      .put(Maps.immutableEntry(4, "Fat"))
      .put(Maps.immutableEntry(5, "Str"))
      .put(Maps.immutableEntry(6, "Hea"))
      .put(Maps.immutableEntry(7, "Dmg"))
      .put(Maps.immutableEntry(8, "Jum"))
      .put(Maps.immutableEntry(9, "Nau"))
      .put(Maps.immutableEntry(10, "Reg"))
      .put(Maps.immutableEntry(11, "Res"))
      .put(Maps.immutableEntry(12, "Fir"))
      .put(Maps.immutableEntry(13, "Wat"))
      .put(Maps.immutableEntry(14, "Inv"))
      .put(Maps.immutableEntry(15, "Bli"))
      .put(Maps.immutableEntry(16, "NV"))
      .put(Maps.immutableEntry(17, "Hun"))
      .put(Maps.immutableEntry(18, "Wea"))
      .put(Maps.immutableEntry(19, "Poi"))
      .put(Maps.immutableEntry(20, "Wit"))
      .put(Maps.immutableEntry(21, "HBo"))
      .put(Maps.immutableEntry(22, "Abs"))
      .put(Maps.immutableEntry(23, "Sat"))
      .put(Maps.immutableEntry(24, "Glo"))
      .put(Maps.immutableEntry(25, "Lev"))
      .put(Maps.immutableEntry(26, "Luc"))
      .put(Maps.immutableEntry(27, "BLu"))
      .build();
}
